### ISSUE TITLE
Remove Node 14 tests in matrix

### ISSUE THREAD

**Issue by sotojn** [terascope/workflows#11]
After Teraslice got converted to typescript 5.2, it caused an update to scripts that makes it incompatible with node 14. It may be time consider removing node 14 tests entirely from all assets. This would allow for the following updates:

- Updating `scripts` dependency
- Updating `nodegyp` dependency to latest version

**Comment by godber** [comment]
Can you link to some failures that are caused by this problem or document the error specifically so we can all know what it looks like?

**Comment by sotojn** [comment]
> Can you link to some failures that are caused by this problem or document the error specifically so we can all know what it looks like?

Here is CI failing on a `file-assets` PR for a bump on `ts-scripts` 
https://github.com/terascope/file-assets/actions/runs/7387280038/job/20095640289?pr=900

**Comment by godber** [comment]
This PR:

https://github.com/terascope/workflows/pull/12

Closes this issue ...  

So you guys (@sotojn and @busma13) can go back to the assets and make the necessary changes to drop node 14 and 16.

**Comment by godber** [comment]
Oh, from the looks of it, it's the `"@terascope/scripts"` package that required node 18.   So I guess that's the first step across all the assets.
